### ISSUE TITLE
Handling of 'wheel' input event was delayed for 109 ms due to main thread being busy.

### ISSUE THREAD

**Issue by LG0012** [hilongjw/vue-lazyload#109] opened 2017-01-25 15:48 UTC
http://prntscr.com/e0796e
http://prntscr.com/e079cd

I'm not sure if this is a huge problem, but yeah, i got this warning. So i don't know, maybe someone have a solution for this issue?

**Comment by hilongjw** [comment] 2017-02-06 09:46
I think the problem is related to [Passive event listeners](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md)

**Comment by hilongjw** [comment] 2017-02-08 09:12
@LG0012 fixed in [SupportsPassive](https://github.com/hilongjw/vue-lazyload/commit/929fa68272ff030b2e1db665060344d453c9f350)

**Closed by hilongjw** 2017-02-08 09:12 UTC
