### ISSUE TITLE
Unable to get srcset to work as expected

### ISSUE THREAD

**Issue by patric-eberle** [hilongjw/vue-lazyload#238] opened 2018-03-28 12:12 UTC
Using version 1.2.2 with Vue 2.5.15

I'm not able to get srcset to work as expected. The following output without your plugin works as expected in Chrome:

```
<img
  srcset="http://via.placeholder.com/180x150 180w,http://via.placeholder.com/250x150 250w,http://via.placeholder.com/350x150 350w,http://via.placeholder.com/500x150 500w"
  sizes="(min-width: 1024px) 48.828125vw,(min-width: 768px) 45.57291666666667vw,100vw">
```

When replacing `srcset` with `data-srcset` and adding `v-lazy="'http://via.placeholder.com/180x150'"` the `180x150` image is always shown. What do I oversee? Why is `data-srcset` not just converted to `srcset` when the image needs to be loaded and let the browser do the calculation (I know there would have to be a polyfill for older browsers)?

**Comment by Januszpl** [comment] 2018-04-27 17:37
using 1.2.3 with vue 2.5.16 and I'm having the same issue.

**Comment by Januszpl** [comment] 2018-04-27 19:07
Actually it load proper size only on page load. Later when changing viewport size we don't see updating image as we see normally when using normal 
```
<img
        alt="partner"
        srcset="/images/home/about_480.jpg 480w, /images/home/about_768.jpg 768w, /images/home/about.jpg 1371w"
        src="/images/home/about.jpg"
       >
```

**Comment by seuck** [comment] 2018-04-28 17:48
I have the same issue:

```
<img
            class="some__image"
            v-lazy="buildThumbPath(issue)"
            :data-srcset="buildSrcset(issue)">
```

generates:

`<img
  data-srcset="/assets/path/1.jpg, /assets/path/1@2x.jpg 2x" class="some__image"
  data-src="/assets/path/1.jpg"
  src="/assets/path/1.jpg"
  lazy="loaded">`

**srcset** attribute is not created.

**Comment by seuck** [comment] 2018-04-29 10:26
'secret' is not created because this is not how the plugin is supposed to work.
I (and also Januszpl) expected that 'data-srcset' was simply transformed in 'srcset' and let the browser pick the right image but instead the vue-lazyload tries to guess which image in 'srcset' list is the most appropriate and inject it into 'src' attribute.
Al the logic is inside utils.js/getBestSelectionFromSrcset().
Unfortunately this only support width descriptor, not pixel density descriptor.

So a workaround is changing from:
`data-srcset="/assets/path/1.jpg, /assets/path/1@2x.jpg 2x"`

to
`data-srcset="/assets/path/1.jpg 100w, /assets/path/1@2x.jpg 200w"`
as long you're lucky enough to know image width beforehand.

**Comment by Eelsie** [comment] 2018-05-02 13:13
Hi! I also have the same issue with version 1.2.3 and vue 2.5.16. Normal `srcset` works fine but `data-srcset` loads always the first image with the lowest resolution.

**Comment by Jones-S** [comment] 2018-08-19 18:03
For me too.
```
<img
      v-lazy="image.sizes.small"
      :data-srcset="`
        ${image.sizes.small} 500w,
        ${image.sizes.medium} 700w,
        ${image.sizes.large} 1000w
      `"
      :alt="image.alt"
      class="SingleImage__image"
    />
```

Would always display the small image no matter which screen size I have.

**Comment by nataliawojtkowska** [comment] 2018-10-15 11:29
+1 on this `:data-srcset` doesn't work for me either

**Comment by jordanegstad** [comment] 2018-10-15 23:09
+1

**Comment by oivinds** [comment] 2018-11-23 09:46
+1

**Comment by inoisy** [comment] 2018-12-13 11:53
+1

**Comment by behnamt** [comment] 2019-01-21 12:50
+1

**Comment by paul-blundell** [comment] 2019-02-04 13:11
I just looked into this as we were having a similar issue and found that if the images container is larger than the largest image in the srcset then the srcset won't be used and instead defaults back to the original src value.

Surely it should default to the largest image available rather than back to the original src value?

**Comment by Jones-S** [comment] 2019-02-08 14:25
This has been around for quite a while and is definitely of a reason not to use this plugin anymore...
Is there anyone who got this problem solved?

**Comment by counterbeing** [comment] 2019-05-08 08:21
I think I have this figured out. I'm going to put in a pull request shortly.

**Comment by counterbeing** [comment] 2019-05-08 08:27
Here is the pull request: https://github.com/hilongjw/vue-lazyload/pull/357

**Comment by counterbeing** [comment] 2019-05-08 08:38
If you want to try my branch for now, feel free to use `npm install https://github.com/counterbeing/vue-lazyload\#patch-238`. That should get you up and running.

**Comment by moteey** [comment] 2019-05-16 07:19
@counterbeing Great work! I installed your patch and it's working perfectly. 👍

Hope it gets merged soon, but it looks like the library is not being maintained at the moment...

**Comment by counterbeing** [comment] 2019-05-16 16:00
@moteey Yeah. It seems to be working without issue for me as well. I'd love to see it merged, but yeah, it does seem like this repo hasn't been getting much attention lately. Maybe @hilongjw should add some collaborators?

**Comment by bartdominiak** [comment] 2019-05-25 17:40
@counterbeing Can you give us an example how to use that? I tried this approach
```vue
    <img
      v-lazy="src400"
      :data-srcset="`
        ${src400} 400w,
        ${src800} 800w,
        ${src1200} 1200w'
      `"
    />

**Comment by zslucky** [comment] 2019-05-27 07:12
@counterbeing  thanks, I used your patch code, looks like only used the large image instead, not responsive?

**Closed** 2019-05-27 12:23 UTC

**Comment by counterbeing** [comment] 2019-05-27 16:49
Well, i know that it is responsive based on it working here: https://www.corylogan.com/sa/20140210_colombia_popayan/

It does not work on window resize, you have to refresh to get the different image. Here's the source for the component that displays each image: 

https://github.com/counterbeing/south-america-blog/blob/a7c3c075970dc0aeb154d87314428bcc764cebec/src/components/Photo.vue

**Comment by zslucky** [comment] 2019-05-28 05:11
@counterbeing thanks so much!  I used [lazysizes](https://github.com/aFarkas/lazysizes) now. it solve my responsive and lazyload issue now.

**Comment by bartdominiak** [comment] 2019-06-01 18:56
@counterbeing I checked your app on multiple viewports and its still fetching the largest one - 1600px, even I'm mobile/tablet.

**Comment by counterbeing** [comment] 2019-06-01 19:00
Interesting, i've just been inspecting it in chrome. Here it is nearly full screen when I inspect:
![image](https://user-images.githubusercontent.com/239798/58752511-d6246a80-847d-11e9-81d8-d78991869e24.png)

And here is the same image when i refresh the page and i have the screen narrowed down to a smaller width: 
![image](https://user-images.githubusercontent.com/239798/58752517-efc5b200-847d-11e9-9be4-a374744d0b9f.png)

Do you have a way for me to specifically reproduce the bug, possibly using chrome?

**Comment by huantransuper** [comment] 2019-06-17 16:51
@counterbeing When I set 375px and 1920px, the 375 image appeared in 1920 screen and vice versa

**Comment by counterbeing** [comment] 2019-06-17 16:53
I'd look at it if you can publish a code example.

**Comment by huantransuper** [comment] 2019-06-17 16:56
`              <img
                 :v-lazy="'experience_1920/home/suggestion/location_8_1559374544.png'"
                 data-srcset="experience_375/home/suggestion/location_8_1559374544.png 375w,
                              experience_1920/home/suggestion/location_8_1559374544.png 1920w"
                 alt=""
              >`
Please help me. Thank you very much

**Comment by counterbeing** [comment] 2019-06-17 16:59
Can you create a working repo, or do you have one. I just want to be able to run a project, and see the problem. I'll happily help if you can get me that! Just make a new vue project with an isolated demo, push it, and i'll pull it and take a look.

**Comment by Ra1nko** [comment] 2019-09-04 14:15
You can use adapter to make data-srcset work i guess
It seems that lazyload don't change data-srcset to srcset by default

`

    Vue.use(VueLazyload, {
      ...
      adapter: {
        loaded ({el}) {
            const srcSet = el.attributes['data-srcset'];
            if (srcSet) {
                el.setAttribute('srcSet', srcSet.value);
            }
        },
      }
    });


`

**Comment by NicolasHofmairT23** [comment] 2021-08-05 10:02
Hi 👋 
I struggled really a lot with adaptive images (srcset) in combination with this library.
This thread finally helped me to understand what happens.

I think it should be explained in the readme/docs that `data-srcset` is **not** used for the native (identically named) browser function **srcset** & **sizes**. (https://developer.mozilla.org/en-US/docs/Web/HTML/Element/img#attr-srcset)

@seuck figured this out in a comment above: Here https://github.com/hilongjw/vue-lazyload/blob/master/src/util.js (Function `getBestSelectionFromSrcset`) calculates in javascript dependent of the actual container width the best srcset. This is cool but should really be explained in the docs. **sizes**-attribute is not needed for this own implementation.
